### ISSUE TITLE
test_poly_2d fail...

### ISSUE THREAD

**Issue by SnoopyJackson** [rdeits/iris-distro#10]
Hi,

I am interested in IRIS algorithm. I have followed the instructions. But when I tried to  run the test_poly_2d, I get an error. 
I am using Windows 8.1 64 bits and Matlab 2015a

I added the .jar mosek in my java path and the matlab directory

>> javaaddpath('C:\Program Files\Mosek\7\tools\platform\win64x86\bin\mosekmatlab.jar');
>> addpath 'C:\Users\Jonathan\Documents\MATLAB\iris-distro-master\matlab'
>> import iris.test.*;
>> test_poly_2d;

and I get 

Undefined function or variable 'cvxgen_ldp_mex'.

Error in iris.least_distance.cvxgen_ldp (line 9)
[vars, ~] = cvxgen_ldp_mex(struct('Y', Y), struct('verbose', 0));

Error in iris.separating_hyperplanes (line 48)
          ystar = iris.least_distance.cvxgen_ldp(ys);

Error in iris.inflate_region (line 32)
  [A, b, infeas_start] = separating_hyperplanes(obstacle_pts, C, d);

Error in iris.test.test_poly_2d (line 22)
[A,b,C,d,results] = inflate_region(obstacle_pts, A_bounds, b_bounds, start, []);

Thank you,

Jonathan

**Comment by rdeits** [comment]
Hi Jonathan,

I'm afraid I haven't tried building IRIS on windows. The error you're getting is because IRIS cannot find its custom QP solver, which should be compiled when you run `make`. But that may not work on Windows. 

Can you first try the following:
* make a directory called `build` in `iris-distro`
* in `iris-distro`, from a command line, run `make`

If that goes well, then we'll be able to make it work. If it doesn't, then you can just edit the code slightly to call a slower solver which does not have to be compiled. If you want to do that, just edit `matlab/+iris/separating_hyperplanes.m` and change the call from `ystar = iris.least_distance.cvxgen_ldp(ys);` to `if isempty(mosek_res)
            [~,mosek_res] = mosekopt('symbcon echo(0)');
          end
          ystar = iris.least_distance.mosek_ldp(ys, mosek_res);`

**Comment by SnoopyJackson** [comment]
Hi, 

Actually there is an error during the compilation..

-- Writing addpath_iris.m and rmpath_iris.m to C:/Users/JoJo/Documents/MATLAB/ir
is-distro-master/iris-distro/build/matlab
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/JoJo/Documents/MATLAB/iris-distro-
master/iris-distro/pod-build
make[1]: *** No rule to make target 'all'.  Stop.
Makefile:29: recipe for target 'all' failed
make: *** [all] Error 2

But with the solver from mosek it is working :)

Thank you !

Jonathan

**Comment by rdeits** [comment]
Ok, I'm glad you got it working. I'm afraid I can't help much with the Windows build issues, since I don't do any development there myself.
