### ISSUE TITLE
/usr/bin/python: No module named iris_wrapper

### ISSUE THREAD

**Issue by barbosafs** [rdeits/iris-distro#75]
I am trying to run the Python wrapper by running `python -m irispy.test.test_iris_2d`. 
However, I cannot make it work. All I get is `/usr/bin/python: No module named iris_wrapper`.
From what I understood, the error happens in `irispy.py`, when trying to import from `.iris_wrapper`.

I tried it in both Ubuntu 16.04 and 18.04. I have installed all the requirements, packages and license specified in the Readme.md file.

Am I missing any step?

Edit 1: Might be related to my problem. I just found a `.gitignore` file under `iris-distro/src/python/irispy` that has only one line, `iris_wrapper.py`.

**Comment by rdeits** [comment]
I think there could be two possible explanations: 

1. You may be loading the python code from the source directory (which doesn't include the compiled `iris_wrapper`) rather than the build directory. Can you try the same operation from `build/install/lib/pythonX.X/dist-packages` ? 

2. You may be using python2 but iris by default builds for python3. Can you try again with `python3`?

**Comment by barbosafs** [comment]
Thank you very much, that was exactly the problem. It is working now.

**Comment by AmithGspn** [comment]
HI @rdeits after seing your two possible explanations. When checked the 1st explanation. I dont have the distribution package for iris_wraper. How to get it in the distribution package?
